### ISSUE TITLE
Import of an existing go project does not configure gopath correctly

### ISSUE THREAD

**Issue by jbuberel** [go-lang-plugin-org/go-lang-idea-plugin#1448]
- I selected File -> Import Project...
- I selected the top level directory of an existing go project:

c:\users\jason\downloads\workspace

- The top level directory for the project contain a src folder with this structure:

src\github.com\jbuberel\gometrics\

- The \gometrics\ directory contain a gometrics.go file (package main).
- When I open that file, I see broken import refrerences:

![image 1](https://cloud.githubusercontent.com/assets/1711364/6701499/cde0ee5c-ccda-11e4-90e1-30072056c66d.png)

- I was expecting that the gopath would be correctly set to the top-level project directory (the directory containing the src folder) so that the import paths in the source code would work properly.

Using plugin version 0.9.176 with Idea 14.0.3 and JDK 1.8.0_25 on Win8.1

**Comment by dlsniper** [comment]
What do you have configured under ```Settings | Languages & Frameworks | Go Libraries```?

**Comment by jbuberel** [comment]
Just the default values - never manually added any paths:

![image 1](https://cloud.githubusercontent.com/assets/1711364/6701575/d96a69d2-ccdb-11e4-8bf3-62a4f47f4b95.png)

**Comment by jbuberel** [comment]
Is the expected behavior that the project folder containing the 'src' folder should be automatically included in the GOPATH information?

That's what I would have hoped for.

**Comment by dlsniper** [comment]
What values do you have in your GOPATH? The plugin adds ```c:\users\jason_000\go\src``` as far as I can tell, but you expect that things in ```c:\users\jason\downloads\workspace``` to be included as well.
Also, am I correct to assume that the project compiles from the command line without issues?
I might be wrong, but you can try to add ```c:\users\jason_downloads\workspace\``` to the ```Go Libraries | Project Libraries ``` section and that should fix it but I still don't fully understand how @zolotov did this part of the plugin so, even if it works, maybe he'll have a different input than me.

**Comment by jbuberel** [comment]
Well, in this case, I was creating a project from existing sources, found in `C:\Users\jason_000\Downloads\workspace`. 

That results in the .idea project folder gets created in that directory: `C:\Users\jason_000\Downloads\workspace\.idea`

So my expectation was that the plugin would add `C:\Users\jason_000\Downloads\workspace\` to the GOPATH automatically at the time of project creation.

**Comment by jbuberel** [comment]
Even after changing the project strucutre to indicate that 'src' is a 'source code folder', the errors are still displayed:

![image 3](https://cloud.githubusercontent.com/assets/1711364/6701761/678f3d4e-ccde-11e4-8ff2-3ce4fcd1ce34.png)

**Comment by dlsniper** [comment]
Can you please confirm that adding the workspace dir to the Project Libraries doesn't help?

**Comment by jbuberel** [comment]
Manually adding `C:\Users\jason_000\Downloads\workspace\` to the Project Libraries fixes import and refernces error.

However, when I run build project, I see errors in the log view:

![image 4](https://cloud.githubusercontent.com/assets/1711364/6701821/3bda7618-ccdf-11e4-878b-2d9bb4071064.png)

**Comment by dlsniper** [comment]
Cool, thanks. I'll leave this for Alexander then :-)

**Comment by zolotov** [comment]
> Manually adding C:\Users\jason_000\Downloads\workspace\ to the Project Libraries fixes import and refernces error.

Yes, it is proper solution. Since you want this directory in GOPATH you have to add it to Go Libraries. Automatically adding project into Go Libraries is very questionable, existing of src-directory doesn't mean anything.

> However, when I run build project, I see errors in the log view

It's not very informative. What's the error message? What's the run configuration that you've run? What're the source files that were trying to compile? 
Also build log also contains the command that IDE tried to run. Just try to do the same thing in console and maybe it's go not IDE fault at all.

**Comment by dlsniper** [comment]
@jbuberel any updates on this? Also, have you updated the plugin meanwhile? There have been lots of changes to runners lately. Thanks.

**Comment by dlsniper** [comment]
I'll close this due to the lack of feedback. Please reopen this if needed. Thank you.
