### ISSUE TITLE
"Type reference" coloring for custom types or interfaces mostly not working

### ISSUE THREAD

**Issue by aka-doode** [go-lang-plugin-org/go-lang-idea-plugin#2403]
Plugin version: 0.11.1197
WebStorm 2016.1
Build #WS-145.258, built on March 16, 2016
JRE: 1.8.0_76-release-b18 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Linux Mint 17.2 Cinnamon-64 bit

According to the editor settings in WebStorm, "Type reference" has a certain color (using Darcula theme) that the type references shall use. For me, they mostly aren't. In the screenshot which contains a few snippets, CreateError is a custom type and is not colored according to the Darcula theme. Neither is http.ResponseWriter, http.Request, httprouter.Params. For some reason, Router is though..

![webstorm_golang](https://cloud.githubusercontent.com/assets/9456137/13907020/e5d0dc0c-eee4-11e5-972a-a074d933a76e.png)

**Comment by zolotov** [comment]
What's the file is it? Is it the part of project or it's part of SDK or library?

**Comment by dlsniper** [comment]
@zolotov I can reproduce this on the following code:
```go
package main

type Demo struct{}

func (demo *Demo)  Hello() {}

func main() {
	_ := Demo{}
}
```

**Comment by aka-doode** [comment]
@zolotov The snippets are from a project of mine.

**Comment by zolotov** [comment]
@aka-doode please try a build from nightly channel (see `pre-release build` section of README for instructions), I think it should be fixed there.

**Comment by aka-doode** [comment]
Sorry for taking so long to reply. I've tested this using...
WebStorm 2016.1.3
Build #WS-145.1616, built on May 27, 2016
JRE: 1.8.0_76-release-b198 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
... and it's not fixed in that version. Should it be?

**Comment by dlsniper** [comment]
@aka-doode. What plugin version do you have? Thanks

**Comment by aka-doode** [comment]
Oh, right, forgot to include that. Sorry.
Plugin version: 0.11.1295 (15.04.2016)
Thought it got updated to a more recent version than that, since I've added both the alpha and nightly repos. Are you not releasing nightly/alphas for WS 11, or is something wrong with my settings?

**Comment by dlsniper** [comment]
That doesn't look correct, nightly releases should be available. I can't look into it right now, sorry. However, double check tge readme for how to get the nightly. Thank you!

**Comment by dlsniper** [comment]
I can't reproduce it in the latest nightly. If it this is still a problem, please open a new issue. Thank you.
