### ISSUE TITLE
Unknown Module Error (IntelliJ 2016.1.1)

### ISSUE THREAD

**Issue by kamronbatman** [go-lang-plugin-org/go-lang-idea-plugin#2428]
- Plugin version (or commit hash): 0.11.1197
- IDE name and version: IntelliJ Ultimate 2016.1.1
- Java version: 1.7
- OS name and version: Mac OSX El Capitan 

- What are you trying to do? Update from IntelliJ 2016.1 to 2016.1.1

- What would you expect to happen? Module will install without errors

- What happens? Get error saying GO_MODULE will be treated as an Unknown Module.

**Comment by zolotov** [comment]
Cannot recreate. Please make sure that go plugin is installed and enabled

**Comment by kamronbatman** [comment]
I removed it and reinstalled it and now everything is working.
It looks like it broke as a result of the update from 2016.1 to 2016.1.1.

**Comment by zolotov** [comment]
will check, thanks

**Comment by dlsniper** [comment]
I'm on nightly and upgraded as well to 2016.1.1 but that didn't happened to me. I was on the 2016.1.1 EAP before that so might be a reason?

**Comment by mindbergh** [comment]
I also got the same problem. Fixed by reinstallation.

**Comment by mgouline** [comment]
In addition to updating from 2016.1 to 2016.1.1, same thing happened to me after upgrading from 15 to 2016.1.

**Comment by Comradin** [comment]
Same problem here, after the latest update, the plugin broke.

Getting the message *"Unknown Module Type, Cannot determine module type ("GO_MODULE") for the module: "my_project" The module will be treated as an Unknown module.*

Even from the Settings -> Languages & Frameworks Tab the Go settings disappeared.

Reinstalling the plugin did help for me, too. Everything seems back to normal.

**Comment by dlsniper** [comment]
All: Have you also updated the plugins when updating the IDE? Usually there's a message to update the plugins on first start after the new version starts. How did you updated the IDE?  Was it via auto-update or a different way? Do you have checks for update enabled?

**Comment by flyingmutant** [comment]
Auto-updated IDE after it prompt to do so. Issue was fixed by plugin reinstallation for me.

**Comment by zolotov** [comment]
Guys "got the same" is not really helpful. Please give more details: initial IDE version, initial plugin version, version IDE after update. Thanks

**Comment by NoICE** [comment]
- OS X 10.11.3
- Java 1.8.0_40-release-b132 x86_64.
- IntelliJ IDEA updated from 2016.1 to 2016.1.1 (via "Update and restart" in update dialog). All plugins up-to-date.

The message "unknown module go" appeared immediately after starting. 

Restarted, nothing, still the same. Pressed "IDEA -> Check for updates" ... offered update of go plugin from 0.11.1197 to 0.11.1197 (yes, that's not a typo). Pressed OK. Idea restarted. Unknown module go.
Pressed Check for updates again and IDEA offered update of go plugin from 0.11.1197 to  0.11.1197. Pressed OK. Idea restarted. Unknown module go.

Searched for this issue here, found it, uninstalled the plugin, restarted idea, install the plugin, restarted idea, go plugin now works.

**Comment by dlsniper** [comment]
@zolotov could it be that it's because there were two updates with the same number? Check the page here: https://plugins.jetbrains.com/plugin/5047?pr=idea&showAllUpdates=true it lists two 0.11.1197. One is valid for 145.257 — 145.257 and one is valid for 145.258 — 145.*

**Comment by zolotov** [comment]
@dlsniper they are in different channels

**Comment by kamronbatman** [comment]
@zolotov I had the same experience.  I updated via auto-update prompt and once I was in 2016.1.1, it prompted me to update Go to the same version.  It actually didn't say whether it updated or not.  I would restart IntelliJ and it would keep prompting me.  That is when I removed it and reinstalled it to fix the issue.

**Comment by kamronbatman** [comment]
@zolotov Also I would like to note that unlike dlsniper, I am **not** on nightly.

**Comment by dlsniper** [comment]
@kamronbatman I'll quote @zolotov on this one:

> Guys "got the same" is not really helpful. Please give more details: initial IDE version, initial plugin version, version IDE after update. Thanks

Please provide the `idea.log` file at least that was at the time of the upgrade so we can get more information about it :) Or if you really remember the before / after installation versions for the plugin..

**Comment by kamronbatman** [comment]
@dlsniper The logs don't say anything about Go, GO_MODULE, Disabled plugins, or Unknown modules.
Also the version is the same before and after the update.  Version is 0.11.1197

**Comment by dlsniper** [comment]
@kamronbatman but still, can you please provide them? If you don't want to share them publicly, ping me on gitter: https://gitter.im/dlsniper Thanks.

**Comment by dlsniper** [comment]
Should we close this?

**Comment by kamronbatman** [comment]
I am ok with it.

**Comment by HaraldNordgren** [comment]
This happened to me just now when updating IntelliJ IDEA.

Reinstalling works. But annoying that this is still happening a year after closing the issue.

**Comment by dlsniper** [comment]
@HaraldNordgren the plugin not being compatible with the IDE is not something it can be controlled. It happens and will happen for various reasons that simply cannot be fixed.
